name: nalgebra CI build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yarn install
        run: corepack enable && yarn
      - name: yarn build
        run: yarn build
