name: parry.rs CI build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yarn install
        run: corepack enable && yarn
      - name: yarn build
        run: yarn build
  test-code-snippets-rust:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - name: clippy examples
        run: cd docs-examples && cargo clippy --examples
